import NewPostModalContainer from "@/components/NewPostModalContainer";
import SideBar from "@/components/ui/SideBar";
import AuthProvider from "@/context/AuthProvider";
import { NewPostModalProvider } from "@/context/NewPostModalContext";
import ThemeProvider from "@/context/ThemeProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`flex ${geistSans.variable} ${geistMono.variable} antialiased `}
			>
				<ThemeProvider>
					<AuthProvider>
						<NewPostModalProvider>
							<SideBar className="bg-base-300 text-base-content" />
							<NewPostModalContainer />
							<main className="w-full px-24 bg-base-100 text-base-content">
								{children}
							</main>
						</NewPostModalProvider>
					</AuthProvider>
					<Toaster
						position="top-right"
						toastOptions={{
							success: { style: { background: "darkgreen", color: "white" } },
							error: { style: { background: "darkred", color: "white" } },
						}}
					/>
				</ThemeProvider>
			</body>
		</html>
	);
}
