import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/context/AuthProvider";
import SideBar from "@/components/ui/SideBar";
import ThemeProvider from "@/context/ThemeProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`flex ${geistSans.variable} ${geistMono.variable} antialiased `}
			>
				<ThemeProvider>
					<AuthProvider>
						<SideBar className="h-dvh bg-light-background dark:bg-dark-background text-light-text-primary dark:text-dark-text-primary border-light-border dark:border-dark-border" />
						<main className="w-full h-dvh px-24 bg-light-background dark:bg-dark-background text-light-text-primary dark:text-dark-text-primary">
							{children}
						</main>
					</AuthProvider>
					<Toaster
						position="top-right"
						toastOptions={{
							success: { style: { background: "darkgreen", color: "white" } },
							error: { style: { background: "darkred", color: "white" } },
						}}
					/>
				</ThemeProvider>
			</body>
		</html>
	);
}
